# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

inhibit_all_warnings!

target 'hackathon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LaundryHub-Driver
pod 'DZNEmptyDataSet'
pod 'Crashlytics'
pod 'SDWebImage'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'Fabric'

end
